#!/usr/bin/env bash
# configure domain zone so that subdomain www points to load-balancer IP lb-01

splitter () {
    TEMP=$(dig "$SUBD" | grep -A1 'ANSWER SECTION:' | tail -1)
    A=$(echo "$TEMP" | awk '{ print $4 }')
    B=$(echo "$TEMP" | awk '{ print $5 }')
}

if [ $# -eq 2 ]
then
    SUBD="$2.$1"
    splitter "$SUBD"
    echo "The subdomain $2 is a $A record and points to $B"
elif [ $# -eq 1 ]
then
    ARR=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${ARR[@]}"
    do
        SUBD="$i.$1"
        splitter "$SUBD"
        echo "The subdomain $i is a $A record and points to $B"
    done
fi
