#!/usr/bin/env bash
# Install nginx on web-01 server and Nginx should be listening on port 80
apt update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
