#!/usr/bin/env bash
# Install nginx on web-01 server and Nginx should be listening on port 80
apt-get -y install
apt-get -y install nginix
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
