#!/usr/bin/env bash
# Install nginx on web-01 server and Nginx should be listening on port 80
# Configure Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
apt update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
