#!/usr/bin/env bash
# Install nginx on web-01 server and Nginx should be listening on port 80
# Configure Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
apt-get -y install
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sed -i "38i\error_page 404 /error_404.html;" /etc/nginx/sites-available/default
service nginx restart
