#!/usr/bin/env bash
# configure web-02 to be identical to web-01
apt-get -y install
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sed -i "38i\error_page 404 /error_404.html;" /etc/nginx/sites-available/default
printf %s "server" {
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default
sudo nginx -s restart
