#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install -y haproxy=2.4.\*
sudo apt update && sudo apt upgrade -y

echo "ENABLED=1" > /etc/default/haproxy

echo "
listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 414-web-01 44.192.44.2 check
	server 414-web-02 3.236.234.46 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
