#!/usr/bin/env bash
# type of network a computer in local is connected to
# type of network that could connect an office in one building to
# another office in a building a few streets away
# network used to connect to browse www.google.com from smartphone
3
2
1
