#!/usr/bin/env bash
#Process and PID file
if [ ! -e /var/run/$myscript.pid ]
then
	echo $$ > /var/run/$myscript.pid
fi
cleanup ()
{
echo "I hate the kill command"
sudo pkill -f /var/run/myscript.pid
}
cleansup ()
{
sudo pkill -f /var/run/myscript.pid
}
cleanups ()
{
echo "Y U no love me?!"
}
trap cleanup SIGTERM
trap cleanups SIGINT
trap cleansup SIGQUIT
while true
do
        echo "To infinity and beyond"
	sleep 2
done
