#!/usr/bin/env bash
#Manage my process
start ()
{
	echo "manage_my_process started"
	echo $$ > /var/run/my_process.pid
}
stop ()
{
	sudo rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart ()
{
	sudo rm -f /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		start ;;
	stop)
		stop ;;
	restart)
		restart ;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
exit $?
