#!/usr/bin/env bash
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i=1
while [[ $i -le 20 ]]
do
	case $i in
		4)
			printf "%s\nbad luck from China\n" "4" ;;
		9)
			printf "%s\nbad luck from Japan\n" "9" ;;
		17)
			printf "%s\nbad luck from Italy\n" "17" ;;
		*)
			echo "$i" ;;
	esac
	((i++))
done
