#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [[ $i -le 20 ]]
do
	case $i in
		4)
			printf "%s\nbad luck from China\n" "4" ;;
		9)
			printf "%s\nbad luck from Japan\n" "9" ;;
		17)
			printf "%s\nbad luck from Italy\n" "17" ;;
		*)
			echo "$i" ;;
	esac
	((i++))
done
