#!/usr/bin/env bash
# displays content of the current directory In a list format
# Where only the part of the name after the first dash is displayed
i="$(ls)"
for j in $i
do
	echo "$j" | cut -d'-' -f2-
done
