#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except 
# TCP port: 22 (SSH), 443(HTTPS SSL), and 80 (HTTP)

sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
