#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except 
# TCP port: 22 (SSH), 443(HTTPS SSL), and 80 (HTTP)
sudo apt update
sudo apt install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
