#!/usr/bin/env bash
# Configure ufw so as to allow TCP port: 22(SSH), 443(HTTPS SSL), and 80(HTTP)
sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw enable
