#!/usr/bin/env bash
# Configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP
sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw enable
# sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 8080 -j REDIRECT --to-port 80
# sudo iptables -A PREROUTING -t nat -p tcp --dport 8080/TCP -j REDIRECT --to-ports 80/TCP
sudo iptables -t nat -I PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80
